/** Wordy phrase -> shorter replacement. An empty replacement means "usually deletable". */
export const WORDY_PHRASES: ReadonlyArray<readonly [string, string]> = [
  ["in order to", "to"],
  ["due to the fact that", "because"],
  ["owing to the fact that", "because"],
  ["in view of the fact that", "because"],
  ["despite the fact that", "although"],
  ["in spite of the fact that", "although"],
  ["a large number of", "many"],
  ["a great deal of", "much"],
  ["a majority of", "most"],
  ["the majority of", "most"],
  ["a number of", "several"],
  ["at this point in time", "now"],
  ["at the present time", "currently"],
  ["at the present moment", "currently"],
  ["in the event that", "if"],
  ["in the near future", "soon"],
  ["has the ability to", "can"],
  ["have the ability to", "can"],
  ["is able to", "can"],
  ["are able to", "can"],
  ["with regard to", "regarding"],
  ["with respect to", "regarding"],
  ["in regard to", "regarding"],
  ["in relation to", "regarding"],
  ["prior to", "before"],
  ["subsequent to", "after"],
  ["for the purpose of", "for"],
  ["for the reason that", "because"],
  ["in the process of", "while"],
  ["on a regular basis", "regularly"],
  ["on a daily basis", "daily"],
  ["in a timely manner", "promptly"],
  ["in close proximity to", "near"],
  ["in the vicinity of", "near"],
  ["take into consideration", "consider"],
  ["take into account", "consider"],
  ["give consideration to", "consider"],
  ["make use of", "use"],
  ["makes use of", "uses"],
  ["is indicative of", "indicates"],
  ["is suggestive of", "suggests"],
  ["conduct an investigation of", "investigate"],
  ["conducted an investigation of", "investigated"],
  ["perform an analysis of", "analyse"],
  ["performed an analysis of", "analysed"],
  ["whether or not", "whether"],
  ["the fact that", ""],
  ["it is important to note that", ""],
  ["it should be noted that", ""],
  ["it is worth noting that", ""],
  ["it is interesting to note that", ""],
  ["it goes without saying that", ""],
  ["needless to say", ""],
  ["as a matter of fact", ""],
  ["each and every", "each"],
  ["first and foremost", "first"],
  ["basic fundamentals", "fundamentals"],
  ["past history", "history"],
  ["future plans", "plans"],
  ["end result", "result"],
  ["final outcome", "outcome"],
  ["completely eliminate", "eliminate"],
  ["absolutely essential", "essential"],
  ["close proximity", "proximity"],
  ["advance planning", "planning"],
  ["join together", "join"],
  ["combine together", "combine"],
  ["repeat again", "repeat"],
  ["revert back", "revert"],
  ["return back", "return"],
  ["summarize briefly", "summarize"],
  ["in my opinion, I think", "I think"],
  ["is of the opinion that", "believes that"],
  ["by means of", "by"],
  ["in the absence of", "without"],
  ["in the case of", "for"],
  ["has a tendency to", "tends to"],
  ["a wide variety of", "many"],
  ["a wide range of", "many"],
  ["so as to", "to"],
  ["with the exception of", "except"],
  ["notwithstanding the fact that", "although"],
  ["for all intents and purposes", ""],
  ["at the end of the day", ""],
];

/** Informal or imprecise wording that reviewers often flag in academic writing. */
export const INFORMAL_PHRASES: ReadonlyArray<readonly [string, string[]]> = [
  ["a lot of", ["many", "much", "numerous"]],
  ["lots of", ["many", "much"]],
  ["tons of", ["many", "much"]],
  ["a bunch of", ["several", "many"]],
  ["kind of", ["somewhat", "rather"]],
  ["sort of", ["somewhat", "rather"]],
  ["pretty much", ["largely", "nearly"]],
  ["gonna", ["going to"]],
  ["wanna", ["want to"]],
  ["kinda", ["somewhat"]],
  ["gotta", ["must", "have to"]],
  ["stuff", ["material", "items"]],
  ["get rid of", ["eliminate", "remove"]],
  ["look into", ["investigate", "examine"]],
  ["find out", ["determine", "establish"]],
  ["figure out", ["determine", "work out"]],
  ["come up with", ["devise", "propose"]],
  ["go up", ["increase", "rise"]],
  ["go down", ["decrease", "fall"]],
  ["a bit", ["slightly", "somewhat"]],
  ["huge", ["substantial", "considerable"]],
  ["nowadays", ["currently", "at present"]],
  ["anyways", ["anyway"]],
  ["okay", ["acceptable", "adequate"]],
];

export const WEAK_WORDS: ReadonlyArray<string> = [
  "very",
  "really",
  "basically",
  "literally",
  "obviously",
  "actually",
  "extremely",
  "totally",
  "definitely",
  "simply",
];

export const CONTRACTIONS: Readonly<Record<string, string>> = {
  "can't": "cannot",
  "won't": "will not",
  "don't": "do not",
  "doesn't": "does not",
  "didn't": "did not",
  "isn't": "is not",
  "aren't": "are not",
  "wasn't": "was not",
  "weren't": "were not",
  "hasn't": "has not",
  "haven't": "have not",
  "hadn't": "had not",
  "shouldn't": "should not",
  "wouldn't": "would not",
  "couldn't": "could not",
  "mustn't": "must not",
  "needn't": "need not",
  "it's": "it is",
  "that's": "that is",
  "there's": "there is",
  "what's": "what is",
  "let's": "let us",
  "we're": "we are",
  "they're": "they are",
  "you're": "you are",
  "i'm": "I am",
  "we've": "we have",
  "they've": "they have",
  "i've": "I have",
  "you've": "you have",
  "we'll": "we will",
  "they'll": "they will",
  "i'll": "I will",
  "it'll": "it will",
  "we'd": "we would",
  "they'd": "they would",
};

/** Unambiguous errors matched as phrases. */
export const CONFUSIONS: ReadonlyArray<readonly [RegExp, string, string]> = [
  [/\b(should|could|would|must|might) of\b/gi, "$1 have", "'of' is a mishearing of 'have' here."],
  [/\balot\b/gi, "a lot", "'alot' is not a word; write 'a lot' (or better, 'many' or 'much')."],
  [/\birregardless\b/gi, "regardless", "'Irregardless' is non-standard."],
  [/\b(more|less|better|worse|greater|higher|lower|larger|smaller|rather|other|fewer|faster|slower) then\b/gi, "$1 than", "Use 'than' for comparisons."],
  [/\btheir (is|are|was|were|will|has|have)\b/gi, "there $1", "'There' (not 'their') introduces existence."],
  [/\bthere (own|data|study|studies|method|methods|approach|findings|analysis)\b/gi, "their $1", "Use 'their' to show possession."],
  [/\bit's own\b/gi, "its own", "Possessive 'its' has no apostrophe."],
  [/\bbased off of\b/gi, "based on", "Use 'based on'."],
  [/\bcomprised of\b/gi, "composed of", "Use 'composed of' or 'comprises'."],
  [/\binfront\b/gi, "in front", "Two words."],
  [/\bin regards to\b/gi, "in regard to", "Use 'in regard to' or 'regarding'."],
  [/\bcould care less\b/gi, "could not care less", "The usual idiom is 'could not care less'."],
  [/\bfor all intensive purposes\b/gi, "for all intents and purposes", "Mis-heard idiom."],
  [/\bits (been|a|an|not|clear|possible|likely|unlikely|important|necessary|difficult|evident|known|true|worth)\b/gi, "it's $1", "'It's' (it is / it has) needs an apostrophe here."],
  [/\b(an|the|no|any|a|significant|positive|negative|strong|large|small|main|overall|direct|indirect) affect (of|on)\b/gi, "$1 effect $2", "Use the noun 'effect' here; 'affect' is usually the verb."],
  [/\b(results|findings|studies|analyses|data sets|datasets|experiments|these results|they|we) (shows|suggests|indicates|demonstrates|reveals|confirms)\b/gi, "$1 $2__STRIP_S", "The verb should agree with the plural subject."],
  [/\b(this|the|our|each|every) (study|result|analysis|model|method|paper|finding|experiment|figure|table) (show|suggest|indicate|demonstrate|reveal|confirm)\b/gi, "$1 $2 $3s", "The verb should agree with the singular subject."],
  [/\b(results|findings|studies|analyses) was\b/gi, "$1 were", "Plural subject: use 'were'."],
  [/\bless (participants|patients|samples|studies|people|subjects|errors|cases|items|observations|students|respondents|individuals|trials|papers)\b/gi, "fewer $1", "Use 'fewer' with things you can count."],
  [/\b(the|a|an|large|small|total|greater|smaller) amount of (participants|patients|samples|studies|people|subjects|errors|cases|items|observations|students|respondents|individuals|trials|papers)\b/gi, "$1 number of $2", "Use 'number of' with things you can count."],
  [/\bet al(?![.\w])/g, "et al.", "'et al.' takes a full stop."],
  [/\bprinciple (investigator|component|components|author|aim|reason|finding|findings)\b/gi, "principal $1", "'Principal' means main; 'principle' means a rule."],
  [/\bcomplimentary (approach|approaches|method|methods|technique|techniques|data|information|evidence|analysis|analyses|role|roles|perspective|perspectives)\b/gi, "complementary $1", "'Complementary' means completing each other; 'complimentary' means praising or free."],
  [/\b(this|the|a) phenomena\b/gi, "$1 phenomenon", "Singular: 'phenomenon' (plural 'phenomena')."],
  [/\b(this|the|a) criteria\b/gi, "$1 criterion", "Singular: 'criterion' (plural 'criteria')."],
  [/\bdependant (variable|variables|on)\b/gi, "dependent $1", "'Dependent' is the adjective."],
  [/\bstatistically significance\b/gi, "statistical significance", "Use the adjective 'statistical' before the noun."],
  [/\bwho's (work|study|data|results|findings|research|paper|papers|contribution|contributions)\b/gi, "whose $1", "'Whose' shows possession; 'who's' means 'who is'."],
  [/\bloose (weight|data|information|accuracy|precision|track)\b/gi, "lose $1", "'Lose' means to misplace or fail to keep; 'loose' means not tight."],
];

/** Likely errors that can occasionally be intended, reported as warnings rather than errors. */
export const LIKELY_CONFUSIONS: ReadonlyArray<readonly [RegExp, string, string]> = [
  [
    /\b(more|less|fewer|better|worse|greater|higher|lower|larger|smaller|faster|slower|earlier|later|longer|shorter|stronger|weaker)(\s+[a-z]+){1,3}\s+then\s+(?=(?:we|they|expected|anticipated|predicted|planned|intended|required|needed|usual|before|previously|reported|those|that|in|at|the|a|our|their|other|ever)\b)/gi,
    "",
    "Possibly 'than': use 'than' for comparisons and 'then' for time.",
  ],
  [/\bdifferent than\b/gi, "different from", "'Different from' is preferred in formal writing."],
];

/** Frequent misspellings that dictionaries also catch, kept here so the checker works with no dictionary. */
export const COMMON_MISSPELLINGS: Readonly<Record<string, string>> = {
  recieve: "receive",
  recieved: "received",
  reciever: "receiver",
  seperate: "separate",
  seperately: "separately",
  occured: "occurred",
  occurence: "occurrence",
  occurences: "occurrences",
  occuring: "occurring",
  definately: "definitely",
  definatly: "definitely",
  accomodate: "accommodate",
  accomodation: "accommodation",
  untill: "until",
  wich: "which",
  teh: "the",
  thier: "their",
  enviroment: "environment",
  enviromental: "environmental",
  goverment: "government",
  begining: "beginning",
  beleive: "believe",
  beleived: "believed",
  existance: "existence",
  publically: "publicly",
  neccessary: "necessary",
  necessery: "necessary",
  neccesary: "necessary",
  experiement: "experiment",
  experiements: "experiments",
  experimential: "experimental",
  sucessful: "successful",
  successfull: "successful",
  sucess: "success",
  succesful: "successful",
  adress: "address",
  agressive: "aggressive",
  apparant: "apparent",
  apparantly: "apparently",
  arguement: "argument",
  assesment: "assessment",
  basicly: "basically",
  calender: "calendar",
  cemetary: "cemetery",
  collegue: "colleague",
  comming: "coming",
  commited: "committed",
  committe: "committee",
  concious: "conscious",
  consistant: "consistent",
  consistancy: "consistency",
  curiousity: "curiosity",
  dilemna: "dilemma",
  disapear: "disappear",
  dissapear: "disappear",
  embarass: "embarrass",
  equiptment: "equipment",
  excersize: "exercise",
  exagerate: "exaggerate",
  familar: "familiar",
  finaly: "finally",
  foward: "forward",
  freind: "friend",
  fullfil: "fulfil",
  garantee: "guarantee",
  gaurd: "guard",
  happend: "happened",
  harrass: "harass",
  heigth: "height",
  hierachy: "hierarchy",
  humourous: "humorous",
  ignorence: "ignorance",
  immediatly: "immediately",
  independant: "independent",
  intresting: "interesting",
  knowlege: "knowledge",
  liason: "liaison",
  libary: "library",
  lenght: "length",
  maintainance: "maintenance",
  millenium: "millennium",
  mispell: "misspell",
  neccessity: "necessity",
  noticable: "noticeable",
  occassion: "occasion",
  occassionally: "occasionally",
  paralel: "parallel",
  parliment: "parliament",
  persistant: "persistent",
  posession: "possession",
  prefered: "preferred",
  prevelant: "prevalent",
  priviledge: "privilege",
  probaly: "probably",
  profesor: "professor",
  pronounciation: "pronunciation",
  publicaly: "publicly",
  realy: "really",
  refered: "referred",
  referal: "referral",
  relevent: "relevant",
  religous: "religious",
  remeber: "remember",
  resistence: "resistance",
  responsability: "responsibility",
  restaraunt: "restaurant",
  rythm: "rhythm",
  sieze: "seize",
  similiar: "similar",
  sincerly: "sincerely",
  speach: "speech",
  strenght: "strength",
  suprise: "surprise",
  surprize: "surprise",
  tendancy: "tendency",
  thouroughly: "thoroughly",
  tommorow: "tomorrow",
  truely: "truly",
  unforseen: "unforeseen",
  unfortunatly: "unfortunately",
  useable: "usable",
  vaccuum: "vacuum",
  wether: "whether",
  wierd: "weird",
  writting: "writing",
  analize: "analyze",
  analisys: "analysis",
  hypotheis: "hypothesis",
  hypotesis: "hypothesis",
  signifigant: "significant",
  significent: "significant",
  statisticly: "statistically",
  algorithim: "algorithm",
  algoritm: "algorithm",
  litature: "literature",
  litterature: "literature",
  methology: "methodology",
  metodology: "methodology",
  reserach: "research",
  reasearch: "research",
  resarch: "research",
  paramater: "parameter",
  paramters: "parameters",
  measurment: "measurement",
  improvment: "improvement",
  developement: "development",
  environement: "environment",
  acheive: "achieve",
  achive: "achieve",
  acheived: "achieved",
};

/** Base pairs of [British, American]; regular suffix forms are generated. */
const UK_US_BASES: ReadonlyArray<readonly [string, string]> = [
  ["colour", "color"],
  ["behaviour", "behavior"],
  ["favour", "favor"],
  ["labour", "labor"],
  ["neighbour", "neighbor"],
  ["honour", "honor"],
  ["centre", "center"],
  ["fibre", "fiber"],
  ["litre", "liter"],
  ["theatre", "theater"],
  ["defence", "defense"],
  ["offence", "offense"],
  ["catalogue", "catalog"],
  ["judgement", "judgment"],
  ["sulphur", "sulfur"],
  ["aluminium", "aluminum"],
  ["grey", "gray"],
  ["paediatric", "pediatric"],
  ["oestrogen", "estrogen"],
  ["haemoglobin", "hemoglobin"],
  ["anaemia", "anemia"],
  ["oedema", "edema"],
  ["foetus", "fetus"],
  ["manoeuvre", "maneuver"],
  ["mould", "mold"],
  ["plough", "plow"],
  ["tyre", "tire"],
];

/** Exact pairs where generated suffix forms would be wrong (doubled letters, irregular verbs). */
const UK_US_EXACT: ReadonlyArray<readonly [string, string]> = [
  ["modelling", "modeling"],
  ["modelled", "modeled"],
  ["labelling", "labeling"],
  ["labelled", "labeled"],
  ["travelling", "traveling"],
  ["travelled", "traveled"],
  ["traveller", "traveler"],
  ["cancelled", "canceled"],
  ["cancelling", "canceling"],
  ["fulfil", "fulfill"],
  ["fulfils", "fulfills"],
  ["enrol", "enroll"],
  ["enrols", "enrolls"],
  ["analyse", "analyze"],
  ["analysed", "analyzed"],
  ["analysing", "analyzing"],
  ["catalogued", "cataloged"],
  ["cataloguing", "cataloging"],
];

const UK_US_SUFFIXES = ["", "s", "ed", "ing", "al", "ally", "able", "ably", "ful", "ite", "ites", "hood", "ly"];

/** -ise/-ize families: stem plus the British ending forms. */
const IZE_STEMS = [
  "organ",
  "real",
  "recogn",
  "summar",
  "util",
  "standard",
  "optim",
  "general",
  "categor",
  "character",
  "normal",
  "visual",
  "minim",
  "maxim",
  "emphas",
  "hypothes",
  "synthes",
  "special",
  "priorit",
  "random",
  "harmon",
  "final",
  "formal",
  "internation",
  "local",
  "neutral",
  "stabil",
  "central",
  "custom",
  "material",
  "memor",
  "critic",
  "capital",
  "digit",
  "author",
  "institution",
  "mobil",
  "modern",
  "sensit",
  "social",
  "civil",
  "colon",
  "equal",
  "fertil",
  "ideal",
  "immun",
  "industrial",
  "legal",
  "magnet",
  "monopol",
  "moral",
  "natural",
  "penal",
  "polar",
  "popular",
  "revolution",
  "scrutin",
  "subsid",
  "symbol",
  "sympath",
  "temporal",
  "urban",
  "vandal",
  "verbal",
  "vital",
];

const IZE_ENDINGS: ReadonlyArray<readonly [string, string]> = [
  ["ise", "ize"],
  ["ises", "izes"],
  ["ised", "ized"],
  ["ising", "izing"],
  ["isation", "ization"],
  ["isations", "izations"],
];

export interface SpellingVariantMaps {
  /** British form -> American form. */
  uk: ReadonlyMap<string, string>;
  /** American form -> British form. */
  us: ReadonlyMap<string, string>;
}

function buildVariantMaps(): SpellingVariantMaps {
  const uk = new Map<string, string>();
  const us = new Map<string, string>();
  const add = (ukForm: string, usForm: string) => {
    if (ukForm === usForm) return;
    uk.set(ukForm, usForm);
    us.set(usForm, ukForm);
  };
  for (const [ukBase, usBase] of UK_US_BASES) {
    for (const suffix of UK_US_SUFFIXES) add(ukBase + suffix, usBase + suffix);
  }
  for (const [ukForm, usForm] of UK_US_EXACT) add(ukForm, usForm);
  for (const stem of IZE_STEMS) {
    for (const [ukEnd, usEnd] of IZE_ENDINGS) add(stem + ukEnd, stem + usEnd);
  }
  return { uk, us };
}

export const SPELLING_VARIANTS: SpellingVariantMaps = buildVariantMaps();

/** Acronyms nearly every reader knows, so they never need defining. */
export const COMMON_ACRONYMS: ReadonlySet<string> = new Set(
  (
    "DNA RNA USA UK EU UN US PDF HTML CSS URL HTTP HTTPS CPU GPU RAM ROM AI ML API SQL XML JSON CSV USB WIFI GPS TV PC OS IT " +
    "ID PH CO CO2 NASA WHO CDC FDA NIH NSF ISO IEEE ACM ANOVA IQ CEO PHD MSC BSC MD ICU HIV AIDS COVID MRI CT PCR ATP " +
    "AM PM BC AD OK ETC VS LED LCD OLED SMS MMS PIN ATM VAT GDP GNP CAGR ROI KPI FAQ DIY ASAP RSVP AKA FYI"
  ).split(" "),
);
