"""Writes src/core/detector/model-weights.ts from trained logistic-regression weights.

Usage: python scripts/train/export-model.py weights.npy dense_norm.npy likely_ai likely_human "description"
weights.npy holds HASH_SIZE + NDENSE coefficients followed by the intercept (see train.py).
"""
import base64, json, sys
import numpy as np

HASH = 1 << 18
w = np.load(sys.argv[1])
norm = np.load(sys.argv[2])
likely_ai, likely_human = float(sys.argv[3]), float(sys.argv[4])
trained_on = sys.argv[5]
hashed, dense, bias = w[:HASH], w[HASH:-1], float(w[-1])
scale = float(np.abs(hashed).max() / 127.0)
q = np.clip(np.round(hashed / scale), -127, 127).astype(np.int8)
model = {
    "version": "1",
    "weights": base64.b64encode(q.tobytes()).decode(),
    "scale": scale,
    "bias": bias,
    "dense": {"weights": [round(float(x), 6) for x in dense], "mean": [round(float(x), 6) for x in norm[0]], "sd": [round(float(x), 6) for x in norm[1]], "factor": 0.3},
    "thresholds": {"likelyAi": likely_ai, "likelyHuman": likely_human},
    "trainedOn": trained_on,
}
with open("src/core/detector/model-weights.ts", "w") as f:
    f.write("// Generated by scripts/train/export-model.py. Do not edit by hand.\n")
    f.write('import type { ModelData } from "./model.ts";\n\n')
    f.write("export const MODEL: ModelData = " + json.dumps(model) + ";\n")
print("exported, scale", scale, "nonzero", int((q != 0).sum()))
