/**
 * "Tortured phrases": established terms mangled by synonym-swapping paraphrasing tools, such as "counterfeit
 * consciousness" for "artificial intelligence". They are a strong sign that text was run through such a tool to
 * hide its source (Cabanac, Labbé and Magazinov, 2021, arXiv:2107.06751). The list is curated to phrases that
 * do not occur in ordinary writing; ambiguous ones are left out.
 */
const PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["counterfeit consciousness", "artificial intelligence"],
  ["man-made consciousness", "artificial intelligence"],
  ["fake consciousness", "artificial intelligence"],
  ["profound learning", "deep learning"],
  ["profound neural organization", "deep neural network"],
  ["profound support learning", "deep reinforcement learning"],
  ["support learning", "reinforcement learning"],
  ["move learning", "transfer learning"],
  ["regulated learning", "supervised learning"],
  ["unaided learning", "unsupervised learning"],
  ["semi-regulated learning", "semi-supervised learning"],
  ["irregular woodland", "random forest"],
  ["arbitrary woodland", "random forest"],
  ["colossal information", "big data"],
  ["enormous information", "big data"],
  ["neural organization", "neural network"],
  ["fake neural organization", "artificial neural network"],
  ["counterfeit neural organization", "artificial neural network"],
  ["convolutional neural organization", "convolutional neural network"],
  ["intermittent neural organization", "recurrent neural network"],
  ["long momentary memory", "long short-term memory"],
  ["bolster vector machine", "support vector machine"],
  ["uphold vector machine", "support vector machine"],
  ["k-closest neighbor", "k-nearest neighbour"],
  ["k-closest neighbour", "k-nearest neighbour"],
  ["choice tree", "decision tree"],
  ["straight relapse", "linear regression"],
  ["direct relapse", "linear regression"],
  ["strategic relapse", "logistic regression"],
  ["calculated relapse", "logistic regression"],
  ["hereditary calculation", "genetic algorithm"],
  ["subterranean insect state", "ant colony"],
  ["subterranean insect province", "ant colony"],
  ["molecule swarm", "particle swarm"],
  ["slope plummet", "gradient descent"],
  ["angle plunge", "gradient descent"],
  ["stochastic angle", "stochastic gradient"],
  ["misfortune work", "loss function"],
  ["enactment work", "activation function"],
  ["actuation work", "activation function"],
  ["disarray lattice", "confusion matrix"],
  ["exactness and review", "precision and recall"],
  ["accuracy and review", "precision and recall"],
  ["grouping exactness", "classification accuracy"],
  ["order precision", "classification accuracy"],
  ["highlight extraction", "feature extraction"],
  ["highlight choice", "feature selection"],
  ["include determination", "feature selection"],
  ["dimensionality decrease", "dimensionality reduction"],
  ["head part examination", "principal component analysis"],
  ["vital part investigation", "principal component analysis"],
  ["shrouded markov model", "hidden Markov model"],
  ["concealed markov model", "hidden Markov model"],
  ["bayesian organization", "Bayesian network"],
  ["fluffy rationale", "fuzzy logic"],
  ["fluffy set", "fuzzy set"],
  ["bunch examination", "cluster analysis"],
  ["mean square blunder", "mean square error"],
  ["mean squared blunder", "mean squared error"],
  ["root mean square blunder", "root mean square error"],
  ["outright blunder", "absolute error"],
  ["supreme blunder", "absolute error"],
  ["euclidean separation", "Euclidean distance"],
  ["cosine closeness", "cosine similarity"],
  ["likelihood thickness", "probability density"],
  ["likelihood conveyance", "probability distribution"],
  ["typical conveyance", "normal distribution"],
  ["flag to commotion", "signal to noise"],
  ["sign to clamor", "signal to noise"],
  ["signal to clamor", "signal to noise"],
  ["haze figuring", "cloud computing"],
  ["cloud figuring", "cloud computing"],
  ["edge figuring", "edge computing"],
  ["quantum figuring", "quantum computing"],
  ["equal figuring", "parallel computing"],
  ["dispersed figuring", "distributed computing"],
  ["versatile organization", "mobile network"],
  ["remote organization", "wireless network"],
  ["remote sensor organization", "wireless sensor network"],
  ["parcel misfortune", "packet loss"],
  ["bundle misfortune", "packet loss"],
  ["web of things", "Internet of Things"],
  ["savvy city", "smart city"],
  ["savvy matrix", "smart grid"],
  ["brilliant matrix", "smart grid"],
  ["pc vision", "computer vision"],
  ["picture handling", "image processing"],
  ["picture division", "image segmentation"],
  ["picture characterization", "image classification"],
  ["picture grouping", "image classification"],
  ["article location", "object detection"],
  ["face acknowledgment", "face recognition"],
  ["facial acknowledgment", "facial recognition"],
  ["discourse acknowledgment", "speech recognition"],
  ["regular language handling", "natural language processing"],
  ["normal language handling", "natural language processing"],
  ["characteristic language preparing", "natural language processing"],
  ["notion examination", "sentiment analysis"],
  ["assessment examination", "sentiment analysis"],
  ["feeling investigation", "sentiment analysis"],
  ["content order", "text classification"],
  ["interpersonal organization", "social network"],
  ["inquiry motor", "search engine"],
  ["working framework", "operating system"],
  ["programming designing", "software engineering"],
  ["focal handling unit", "central processing unit"],
  ["illustrations preparing unit", "graphics processing unit"],
  ["designs handling unit", "graphics processing unit"],
  ["irregular access memory", "random access memory"],
  ["digital assault", "cyber attack"],
  ["interruption location", "intrusion detection"],
  ["interruption discovery", "intrusion detection"],
  ["disavowal of administration", "denial of service"],
  ["forswearing of administration", "denial of service"],
  ["mystery key", "secret key"],
  ["open key cryptography", "public key cryptography"],
  ["bosom malignant growth", "breast cancer"],
  ["bosom disease", "breast cancer"],
  ["bosom peril", "breast cancer"],
  ["lung malignant growth", "lung cancer"],
  ["prostate malignant growth", "prostate cancer"],
  ["circulatory strain", "blood pressure"],
  ["kidney disappointment", "kidney failure"],
  ["renal disappointment", "renal failure"],
  ["heart disappointment", "heart failure"],
  ["insulin opposition", "insulin resistance"],
  ["oxidative pressure", "oxidative stress"],
  ["invulnerable framework", "immune system"],
  ["invulnerable reaction", "immune response"],
  ["quality articulation", "gene expression"],
  ["undeveloped cell", "stem cell"],
  ["immature microorganism", "stem cell"],
  ["anti-infection obstruction", "antibiotic resistance"],
  ["anti-microbial opposition", "antimicrobial resistance"],
  ["medication conveyance", "drug delivery"],
  ["attractive reverberation imaging", "magnetic resonance imaging"],
  ["processed tomography", "computed tomography"],
  ["registered tomography", "computed tomography"],
  ["dark opening", "black hole"],
  ["worldwide temperature alteration", "global warming"],
  ["ozone harming substance", "greenhouse gas"],
  ["sustainable power source", "renewable energy"],
  ["sun oriented board", "solar panel"],
  ["sun powered cell", "solar cell"],
  ["sun oriented vitality", "solar energy"],
  ["wind vitality", "wind energy"],
  ["vitality utilization", "energy consumption"],
  ["vitality productivity", "energy efficiency"],
  ["force utilization", "power consumption"],
  ["automated elevated vehicle", "unmanned aerial vehicle"],
  ["warm conductivity", "thermal conductivity"],
  ["compressive quality", "compressive strength"],
  ["liquid elements", "fluid dynamics"],
  ["computational liquid elements", "computational fluid dynamics"],
  ["limited component investigation", "finite element analysis"],
  ["limited component examination", "finite element analysis"],
  ["limited component technique", "finite element method"],
  ["warmth move", "heat transfer"],
  ["heat move", "heat transfer"],
  ["inventory network", "supply chain"],
  ["store network", "supply chain"],
  ["choice emotionally supportive network", "decision support system"],
  ["human asset the executives", "human resource management"],
  ["venture the executives", "project management"],
  ["unfamiliar direct venture", "foreign direct investment"],
  ["outside direct speculation", "foreign direct investment"],
];

export interface TorturedPhrase {
  start: number;
  end: number;
  /** The phrase as written. */
  text: string;
  /** The standard term it most likely replaced. */
  expected: string;
}

const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
// Longest first, so "fake neural organization" wins over "neural organization". Spaces and hyphens are
// interchangeable, and the last word may be plural.
const SORTED = [...PAIRS].sort((a, b) => b[0].length - a[0].length);
const RE = new RegExp(
  `(?<![\\p{L}\\p{N}])(?:${SORTED.map(([p]) => escape(p).replace(/(?:\\-| )/g, "[\\s\\-]+")).join("|")})(?:s|es)?(?![\\p{L}\\p{N}])`,
  "giu",
);
const LOOKUP = new Map(PAIRS.map(([p, e]) => [p.replace(/-/g, " "), e]));

export function findTorturedPhrases(text: string): TorturedPhrase[] {
  const out: TorturedPhrase[] = [];
  for (const m of text.matchAll(RE)) {
    const key = m[0].toLowerCase().replace(/[\s-]+/g, " ");
    const expected = LOOKUP.get(key) ?? LOOKUP.get(key.replace(/e?s$/, "")) ?? LOOKUP.get(key.replace(/s$/, ""));
    if (!expected) continue;
    out.push({ start: m.index, end: m.index + m[0].length, text: m[0], expected });
  }
  return out;
}

export const TORTURED_PHRASE_COUNT = PAIRS.length;
