import { extractFeatures, featureTokens, hashFeature, HASH_SIZE, normaliseForDetection } from "./features.ts";
import { MODEL } from "./model-weights.ts";

/**
 * The trained classifier: logistic regression over hashed word and phrasing
 * features plus style measurements. Weights are int8-quantised and shipped as
 * base64 in model-weights.ts (generated by scripts/train/export-model.py).
 */
export interface ModelData {
  version: string;
  /** base64 of HASH_SIZE signed bytes. */
  weights: string;
  /** Multiply a byte by this to get the real weight. */
  scale: number;
  bias: number;
  dense: { weights: number[]; mean: number[]; sd: number[]; factor: number };
  /** Probability thresholds chosen on held-out human text. */
  thresholds: { likelyAi: number; likelyHuman: number };
  trainedOn: string;
}

let decoded: Float32Array | null = null;

function weights(): Float32Array {
  if (decoded) return decoded;
  const bytes = base64ToBytes(MODEL.weights);
  const out = new Float32Array(HASH_SIZE);
  for (let i = 0; i < HASH_SIZE && i < bytes.length; i++) {
    const b = bytes[i] as number;
    out[i] = (b > 127 ? b - 256 : b) * MODEL.scale;
  }
  decoded = out;
  return out;
}

function base64ToBytes(b64: string): Uint8Array {
  if (typeof atob === "function") {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  return new Uint8Array(Buffer.from(b64, "base64"));
}

const sigmoid = (x: number) => 1 / (1 + Math.exp(-x));

/** Log-odds that a passage was machine-written, according to the trained model alone. */
export function modelLogit(text: string): number {
  const f = extractFeatures(normaliseForDetection(text).text);
  const w = weights();
  let z = MODEL.bias;
  f.indices.forEach((idx, k) => {
    z += (w[idx] as number) * (f.values[k] as number);
  });
  const d = MODEL.dense;
  f.dense.forEach((v, k) => {
    z += (d.weights[k] ?? 0) * ((v - (d.mean[k] ?? 0)) / (d.sd[k] ?? 1)) * d.factor;
  });
  return z;
}

export function modelProbability(text: string): number {
  return sigmoid(modelLogit(text));
}

export interface WindowScore {
  start: number;
  end: number;
  probability: number;
}

/**
 * Scores a long text in overlapping windows of about `size` words, the length the
 * model was trained on. Returns one probability per window.
 */
export function scoreWindows(text: string, size = 300, step = 200): WindowScore[] {
  const words = [...text.matchAll(/\S+/g)];
  if (words.length === 0) return [];
  const out: WindowScore[] = [];
  for (let i = 0; ; i += step) {
    const slice = words.slice(i, i + size);
    const first = slice[0];
    const last = slice[slice.length - 1];
    if (!first || !last) break;
    const start = first.index ?? 0;
    const end = (last.index ?? 0) + last[0].length;
    out.push({ start, end, probability: modelProbability(text.slice(start, end)) });
    if (i + size >= words.length) break;
  }
  return out;
}

/** The words and phrases in a passage that pushed the model most towards "machine-written". */
export function topContributors(text: string, limit = 8): Array<{ phrase: string; weight: number }> {
  const tokens = featureTokens(normaliseForDetection(text).text);
  const w = weights();
  const seen = new Map<string, number>();
  for (let i = 0; i < tokens.length; i++) {
    const a = tokens[i] as string;
    if (/^[\p{L}]{3,}$/u.test(a)) seen.set(a, Math.max(seen.get(a) ?? -Infinity, w[hashFeature(`u:${a}`)] as number));
    const b = tokens[i + 1];
    if (b && /^[\p{L}]/u.test(a) && /^[\p{L}]/u.test(b)) seen.set(`${a} ${b}`, Math.max(seen.get(`${a} ${b}`) ?? -Infinity, w[hashFeature(`b:${a} ${b}`)] as number));
  }
  return [...seen.entries()]
    .filter(([, v]) => v > 0)
    .sort((x, y) => y[1] - x[1])
    .slice(0, limit)
    .map(([phrase, weight]) => ({ phrase, weight: Math.round(weight * 100) / 100 }));
}

export const MODEL_INFO = { version: MODEL.version, trainedOn: MODEL.trainedOn, thresholds: MODEL.thresholds };
